# Generated by Django 2.2.10 on 2020-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castvote',
            name='ipfs_hash',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='castvote',
            name='ipfs_tinyhash',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
