# Generated by Django 2.2.10 on 2020-03-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0002_auto_20200321_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castvote',
            name='ipfs_hash',
        ),
        migrations.RemoveField(
            model_name='castvote',
            name='ipfs_tinyhash',
        ),
    ]
