# Generated by Django 2.2.10 on 2020-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0005_auto_20200325_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='deploy_transaction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
