# Generated by Django 2.2.10 on 2020-03-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0007_auto_20200327_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_pubkey_added_to_contract',
        ),
        migrations.AddField(
            model_name='election',
            name='election_pubkey_hash',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='election_pubkey_transaction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
