# Generated by Django 2.2.10 on 2020-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0009_castvote_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='tx_hash',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
