# Generated by Django 2.2.10 on 2020-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0010_voter_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='uuid_hex',
            field=models.CharField(default='0x', max_length=50),
        ),
    ]
