# Generated by Django 2.2.10 on 2020-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0011_voter_uuid_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='uuid_hex',
            field=models.CharField(max_length=50),
        ),
    ]
