# Generated by Django 2.2.10 on 2020-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0013_auto_20200406_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='voters_added_to_contract',
        ),
        migrations.AddField(
            model_name='election',
            name='voters_added_transaction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
