# Generated by Django 2.2.10 on 2020-04-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helios', '0015_election_voters_who_voted_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='uuid_hex',
            new_name='user_id_hash',
        ),
    ]
